### ISSUE TITLE
WebSocket

### ISSUE THREAD

**Issue by xander9112** [ndabAP/Vue.js-with-Sails.js-backend-example-project#12]
Can you add vue-socket.io - https://github.com/MetinSeylan/Vue-Socket.io to this project with example?

**Comment by ndabAP** [comment]
Thanks for your request.

Do you have a particular use case for sockets inside this project?

**Comment by rito** [comment]
I'm also interested in vue socket. But I'm studying to build an architecture like this:
https://github.com/rito/Arquitetura-Alvo.

**Comment by xander9112** [comment]
I found this package https://www.npmjs.com/package/vue-sails it's sails.io for vue. But it's not working when I start web server from frontend? only from backend

**Comment by JigSawFr** [comment]
Could be great ! :)

**Comment by ndabAP** [comment]
Good news :100: Socket.IO is now implemented in the current release. Click on `Help` at the navigation bar. Currently, only the desktop is supported. Feel free to submit pull requests for a mobile version. Happy coding!
