### ISSUE TITLE
Invalid package name "bcryptjs "

### ISSUE THREAD

**Issue by markuman** [ndabAP/Vue.js-with-Sails.js-backend-example-project#13]
$ git diff
	diff --git a/backend/package.json b/backend/package.json
	index 63cad71..bfcfcc5 100644
	--- a/backend/package.json
	+++ b/backend/package.json
	@@ -4,7 +4,7 @@
	   "version": "0.0.0",
	   "description": "Product paradise",
	   "dependencies": {
	-    "bcryptjs ": "~2.3.0",
	+    "bcryptjs": "~2.3.0",
		 "chai": "^4.1.0",
		 "crypto": "0.0.3",
		 "faker": "^4.1.0",

**Comment by ndabAP** [comment]
Thanks, fixed in the next release.
