### ISSUE TITLE
Plaintext password

### ISSUE THREAD

**Issue by Dave3of5** [ndabAP/Vue.js-with-Sails.js-backend-example-project#4]
The password in this project is stored in plain text.

Please hash the password with something like bcrypt.

I'm putting this here as this project is the top in google search for "sailsjs and vuejs"

**Comment by ndabAP** [comment]
Hey @Dave3of5. Thank you for the issue. I got password hashing on my [to do list](https://github.com/ndabAP/Vue.js-with-Sails.js-backend-example-project/blob/master/README.md#to-do).

Until I find time to do it feel free to make a pull request.
