### ISSUE TITLE
error with MongoDB

### ISSUE THREAD

**Issue by rito** [ndabAP/Vue.js-with-Sails.js-backend-example-project#6]
After install your code, I changed the connections .js and included the mongoDb:

```
  MongodbServer: {
     adapter: 'sails-mongo',
     host: 'localhost',
     port: 27017,
  //   user: 'username', //optional
  //   password: 'password', //optional
     database: 'testeShopVueSails' //optional
  },
```

I instaled the mongo-sails, and change the models to use MongoDB:
```

module.exports = {
  //connection: 'localDiskDb',
  connection: 'MongodbServer',
```

After this, The site don't show the products....

**Comment by ndabAP** [comment]
Hi @rito. Do you mean new created products by you or the existing ones?

**Comment by rito** [comment]
Both. 

Look the images...

![captura de tela 2017-07-20 as 13 14 54](https://user-images.githubusercontent.com/82632/28427779-b6bca5f2-6d4d-11e7-9e8d-b726cdaddc18.png)
![captura de tela 2017-07-20 as 13 15 16](https://user-images.githubusercontent.com/82632/28427780-b6bf24ee-6d4d-11e7-8d32-61a2eb5a0e33.png)
![captura de tela 2017-07-20 as 13 15 56](https://user-images.githubusercontent.com/82632/28427782-b6c44adc-6d4d-11e7-827e-7d63b1d0d2b2.png)
![captura de tela 2017-07-20 as 13 16 31](https://user-images.githubusercontent.com/82632/28427781-b6c16b0a-6d4d-11e7-9e46-790d4033ba75.png)


Another doubt is why we can see the Web View in both ports (8080 and 1337). i think the correct is only in 8080. the 1337 port is only for API, or NOT???

Look the files changed:

In Models I changed this:
![captura de tela 2017-07-20 as 13 19 22](https://user-images.githubusercontent.com/82632/28427967-30e9b6d0-6d4e-11e7-8af0-8ce4bc128d5c.png)

And in connections I included this:
![captura de tela 2017-07-20 as 13 19 39](https://user-images.githubusercontent.com/82632/28427979-3cc234c8-6d4e-11e7-9fb4-e7898824e888.png)



Thanks...

**Comment by ndabAP** [comment]
Port 8080 is for Vue.js development, Port 1337 is used by Sails.js and yes, it's the backend part. When you deploy the application you primarily Sails.js with Vue.js inside of it (with command `npm run build`). 

So, visiting localhost:1337 is like visiting your production environment.

According to your picture you can create products. The reason that the default products don't show might be the hard coded `id`, which MongoDB can't understand. Check this file to see the fixtures:

https://github.com/ndabAP/Vue.js-with-Sails.js-backend-example-project/blob/master/backend/config/bootstrap.js

**Comment by rito** [comment]
okz. thanks.
Don't work with create a list of products. But if I create manually inside system works.

thanks.
